"""Q3 continuous service optimization extended to Q4 directional coverage.

Reference: Q3/third algorithm/bayes_tsp/sectors.py and refinement.py at 242b878.
The Q4 hull-cone constraints below are new, not omnidirectional exclusion cuts.
"""
import math
import numpy as np
from scipy.optimize import minimize
from scipy.spatial import ConvexHull


def station_constraints(certificate, other_stations):
    """A convex sufficient feasible set for replacing ONE missing scan station.

    Other stations are eligible only if they reach the ENTIRE original cell.
    For an uncovered vertex v, v in conv(others,q) iff q-v is in the opposite
    cone generated by others-v. In 2D a pointed cone has two linear boundaries.
    Distance constraints make q eligible throughout every affected cell.
    """
    others = np.asarray(other_stations).reshape(-1, 2)
    prepared = certificate.prepare(others)
    covered, _ = certificate.evaluate_prepared(prepared)
    eligible = prepared[1]
    required_vertices, normals, bounds = [], [], []
    for i in np.flatnonzero(~covered):
        polygon = certificate.vertices[i]
        required_vertices.extend(polygon)
        stations = others[eligible[i]]
        if len(stations) < 2:
            return None  # A lower-dimensional cone cannot cover a 2D cell.
        for vertex in polygon:
            delta = stations-vertex
            norms = np.linalg.norm(delta, axis=1)
            if np.any(norms == 0.):
                continue
            angle = np.arctan2(delta[:, 1], delta[:, 0]) % math.tau
            order = np.argsort(angle)
            sorted_angle = angle[order]
            gaps = np.diff(np.r_[sorted_angle, sorted_angle[0]+math.tau])
            j = int(np.argmax(gaps))
            if gaps[j] < math.pi-1e-10:
                continue  # Already strictly in the other-station hull.
            if gaps[j] <= math.pi+1e-10:
                return None  # Degenerate hull boundary: keep previous safe plan.
            start = -delta[order[(j+1) % len(order)]]/norms[order[(j+1) % len(order)]]
            end = -delta[order[j]]/norms[order[j]]
            for n in (np.array([start[1], -start[0]]), np.array([-end[1], end[0]])):
                normals.append(n)
                bounds.append(float(n@vertex)-1e-7)
    vertices = np.unique(np.asarray(required_vertices).reshape(-1, 2), axis=0)
    if len(vertices) > 2:
        vertices = vertices[ConvexHull(vertices).vertices]
    return vertices, np.asarray(normals).reshape(-1, 2), np.asarray(bounds)


def optimize_service(current, previous, following, vertices, radius, normals=None, bounds=None):
    """Minimize the two incident legs over disks and optional halfplanes.

    Only feasible strict improvements are returned. If numerical optimization
    slightly violates a boundary, repair toward the known feasible incumbent.
    """
    current, previous = np.asarray(current, float), np.asarray(previous, float)
    vertices = np.asarray(vertices, float).reshape(-1, 2)
    normals = np.empty((0, 2)) if normals is None else normals
    bounds = np.empty(0) if bounds is None else bounds
    def objective(q):
        return float(np.linalg.norm(q-previous)+(0. if following is None else np.linalg.norm(q-following)))
    def gradient(q):
        delta = q-previous
        g = delta/max(np.linalg.norm(delta), 1e-12)
        if following is not None:
            delta = q-following
            g += delta/max(np.linalg.norm(delta), 1e-12)
        return g
    def margin(q):
        return np.r_[radius-np.linalg.norm(vertices-q, axis=1), bounds-normals@q]
    def jac(q):
        delta = vertices-q
        return np.vstack([delta/np.maximum(np.linalg.norm(delta, axis=1)[:, None], 1e-12), -normals])
    if len(vertices)+len(normals) == 0:
        return previous.copy(), {'accepted': True, 'saving_m': objective(current)-objective(previous)}
    if margin(current).min() < 0:
        return current.copy(), {'accepted': False, 'reason': 'incumbent_margin'}
    result = minimize(objective, current, jac=gradient, method='SLSQP',
                      constraints=[{'type': 'ineq', 'fun': margin, 'jac': jac}],
                      options={'maxiter': 35, 'ftol': 1e-6})
    if not np.isfinite(result.x).all():
        return current.copy(), {'accepted': False, 'reason': 'nonfinite'}
    proposal = result.x
    if margin(proposal).min() < 0:
        lo, hi = 0., 1.
        for _ in range(40):
            mid = (lo+hi)/2
            if margin(current+mid*(proposal-current)).min() >= 0: lo = mid
            else: hi = mid
        proposal = current+lo*(proposal-current)
    accepted = bool(margin(proposal).min() >= 0 and objective(proposal) < objective(current)-1e-5)
    point = proposal if accepted else current
    return point, {'accepted': accepted, 'saving_m': objective(current)-objective(point),
                   'optimizer_success': bool(result.success)}
